# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false

# Minecraft
mc_version=1.21
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.2)
mod_license=All Rights Reserved
mod_credits= Shaydeejay
mod_issue_tracker=blank
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/jahdoo
mod_logo_file=blank
mod_description=A Minecraft magic mod.

# Neoforge
neo_version=21.1.219
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

# Mappings
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

# Jahdoo Mod
mod_id=jahdoo
mod_version=1.21-1.0
mod_group_id=org.shaydee
mod_authors=Shaydeejay

# Jahdoo mods.toml
mod_name=Jahdoo

# Jahdoo Mod Dependencies
geckolib_version=4.8.3
dev_auth_version = 1.2.1
arcade_version = 0.5.1
curios_version = 9.4.2+1.21.1
loot_beams_version = 0.5.3
shaydeeapi_version = 0.1-ALPHA
ponder_version = 1.0.59

# General
gson_version=2.10.1